version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentiflex-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    networks:
      - dentiflex-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: dentiflex-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./public:/var/www/html/public
    depends_on:
      - web
    networks:
      - dentiflex-network
    restart: unless-stopped

networks:
  dentiflex-network:
    driver: bridge

volumes:
  node_modules:
  next:
